package lojaAuto;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import controller.funcionalidade;
import java.time.Year;
import java.time.format.DateTimeFormatter;
import model.ContaBancaria;
import model.Pessoa;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Carro;
import model.Venda;

/**
 *
 * @author JBP1996 Atec
 */
public class Principal extends javax.swing.JFrame {
    funcionalidade func = new funcionalidade();
    Pessoa p;
    ContaBancaria cb;
    Carro c;
    Venda v;
    public static ArrayList <Pessoa> ap = new ArrayList<Pessoa>();
    public static ArrayList <ContaBancaria> acb = new ArrayList<ContaBancaria>();
    public static ArrayList <Carro> ac = new ArrayList<Carro>();
    public static ArrayList <Venda> av = new ArrayList<Venda>();
    int contalogin=-1;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        func.inserirPessoa(p, ap, "Stand Loja Auto");
        func.inserirConta(cb,ap.size()-1,0, acb);
        Pessoa.setVisible(false);
        Pessoa.setEnabled(false);
        PessoaConta.setVisible(false);
        PessoaConta.setEnabled(false);
        Carro.setVisible(false);
        Carro.setEnabled(false);
        Conta.setVisible(false);
        Conta.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcaoInserir = new javax.swing.ButtonGroup();
        opcaoListar = new javax.swing.ButtonGroup();
        Stand = new javax.swing.JPanel();
        scrollPaneCarros = new javax.swing.JScrollPane();
        tabelaCarros = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        contaComprador = new javax.swing.JTextField();
        vender = new javax.swing.JButton();
        scrollPaneVendas = new javax.swing.JScrollPane();
        tabelaVendas = new javax.swing.JTable();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        data = new javax.swing.JTextField();
        Principal = new javax.swing.JTabbedPane();
        Inserir = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        InserirPessoa = new javax.swing.JRadioButton();
        InserirConta = new javax.swing.JRadioButton();
        InserirPessoaConta = new javax.swing.JRadioButton();
        InserirCarros = new javax.swing.JRadioButton();
        Pessoa = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomeP = new javax.swing.JTextField();
        InserirP = new javax.swing.JButton();
        Conta = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nomeC = new javax.swing.JTextField();
        InserirC = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        saldoC = new javax.swing.JTextField();
        PessoaConta = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nomePC = new javax.swing.JTextField();
        InserirPC = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        saldoPC = new javax.swing.JTextField();
        Carro = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        matricula = new javax.swing.JTextField();
        InserirCa = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        marca = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        modelo = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        ano = new javax.swing.JTextField();
        cor = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        combustivel = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        preco = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        Listar = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        ListarPessoas = new javax.swing.JRadioButton();
        ListarContas = new javax.swing.JRadioButton();
        ListarCarros = new javax.swing.JRadioButton();
        Login = new javax.swing.JPanel();
        LoginPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nconta = new javax.swing.JTextField();
        LoginBtn = new javax.swing.JButton();
        LoginSucesso = new javax.swing.JPanel();
        bemvindo = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        Clientes = new javax.swing.JPanel();
        Depositar = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        quantiadepositar = new javax.swing.JTextField();
        depositarbtn = new javax.swing.JButton();
        Levantar = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        quantialevantar = new javax.swing.JTextField();
        levantarbtn = new javax.swing.JButton();
        Transferir = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        conta = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        quantia = new javax.swing.JTextField();
        transferirbtn = new javax.swing.JButton();
        ListaCarros = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        scrollPaneListaCarros = new javax.swing.JScrollPane();
        tabelaListaCarros = new javax.swing.JTable();

        tabelaCarros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaCarros.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tabelaCarrosComponentShown(evt);
            }
        });
        scrollPaneCarros.setViewportView(tabelaCarros);

        jLabel27.setText("conta de comprador:");

        vender.setText("Vender");
        vender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                venderMouseClicked(evt);
            }
        });

        tabelaVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPaneVendas.setViewportView(tabelaVendas);

        jLabel28.setText("Lista de vendas:");

        jLabel29.setText("Lista de Carros do Stand");

        jLabel30.setText("Data Compra:");

        javax.swing.GroupLayout StandLayout = new javax.swing.GroupLayout(Stand);
        Stand.setLayout(StandLayout);
        StandLayout.setHorizontalGroup(
            StandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StandLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addGroup(StandLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(contaComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vender))
                    .addComponent(scrollPaneCarros, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        StandLayout.setVerticalGroup(
            StandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StandLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPaneCarros, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(StandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(contaComprador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vender))
                .addGap(18, 18, 18)
                .addComponent(jLabel28)
                .addGap(18, 18, 18)
                .addComponent(scrollPaneVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 277));
        setPreferredSize(new java.awt.Dimension(559, 500));

        Pessoa.setVisible(false);
        Pessoa.setEnabled(false);
        Conta.setVisible(false);
        Conta.setEnabled(false);
        PessoaConta.setVisible(false);
        PessoaConta.setEnabled(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inserir");

        opcaoInserir.add(InserirPessoa);
        InserirPessoa.setText("Inserir Pessoa");
        InserirPessoa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                InserirPessoaItemStateChanged(evt);
            }
        });

        opcaoInserir.add(InserirConta);
        InserirConta.setText("Inserir Conta");
        InserirConta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InserirConta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                InserirContaItemStateChanged(evt);
            }
        });

        opcaoInserir.add(InserirPessoaConta);
        InserirPessoaConta.setText("Inserir Pessoa e Conta");
        InserirPessoaConta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                InserirPessoaContaItemStateChanged(evt);
            }
        });

        opcaoInserir.add(InserirCarros);
        InserirCarros.setText("Inserir Carros");
        InserirCarros.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                InserirCarrosItemStateChanged(evt);
            }
        });

        Pessoa.setPreferredSize(new java.awt.Dimension(409, 160));

        jLabel2.setText("Pessoa");

        jLabel3.setText("Nome:");

        InserirP.setText("Inserir");
        InserirP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InserirPMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PessoaLayout = new javax.swing.GroupLayout(Pessoa);
        Pessoa.setLayout(PessoaLayout);
        PessoaLayout.setHorizontalGroup(
            PessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PessoaLayout.createSequentialGroup()
                .addGroup(PessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PessoaLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel2))
                    .addGroup(PessoaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(InserirP)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PessoaLayout.setVerticalGroup(
            PessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(PessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nomeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InserirP))
                .addContainerGap(233, Short.MAX_VALUE))
        );

        Conta.setMinimumSize(new java.awt.Dimension(100, 100));
        Conta.setPreferredSize(new java.awt.Dimension(409, 160));

        jLabel4.setText("Conta");

        jLabel5.setText("Nome:");

        InserirC.setText("Inserir");
        InserirC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InserirCMouseClicked(evt);
            }
        });

        jLabel6.setText("Saldo:");

        javax.swing.GroupLayout ContaLayout = new javax.swing.GroupLayout(Conta);
        Conta.setLayout(ContaLayout);
        ContaLayout.setHorizontalGroup(
            ContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContaLayout.createSequentialGroup()
                .addGroup(ContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContaLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel4))
                    .addGroup(ContaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saldoC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(InserirC)))
                .addContainerGap(308, Short.MAX_VALUE))
        );
        ContaLayout.setVerticalGroup(
            ContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(ContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nomeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(saldoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InserirC))
                .addContainerGap(202, Short.MAX_VALUE))
        );

        PessoaConta.setMinimumSize(new java.awt.Dimension(100, 100));
        PessoaConta.setPreferredSize(new java.awt.Dimension(409, 160));

        jLabel7.setText("Pessoa e Conta");

        jLabel8.setText("Nome:");

        InserirPC.setText("Inserir");
        InserirPC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InserirPCMouseClicked(evt);
            }
        });

        jLabel9.setText("Saldo:");

        javax.swing.GroupLayout PessoaContaLayout = new javax.swing.GroupLayout(PessoaConta);
        PessoaConta.setLayout(PessoaContaLayout);
        PessoaContaLayout.setHorizontalGroup(
            PessoaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PessoaContaLayout.createSequentialGroup()
                .addGroup(PessoaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PessoaContaLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel7))
                    .addGroup(PessoaContaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomePC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PessoaContaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saldoPC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(InserirPC)))
                .addContainerGap(262, Short.MAX_VALUE))
        );
        PessoaContaLayout.setVerticalGroup(
            PessoaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PessoaContaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(PessoaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(nomePC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PessoaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(saldoPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InserirPC))
                .addContainerGap(202, Short.MAX_VALUE))
        );

        Carro.setPreferredSize(new java.awt.Dimension(409, 160));

        jLabel19.setText("Carro");

        jLabel20.setText("Matricula:");

        InserirCa.setText("Inserir");
        InserirCa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InserirCaMouseClicked(evt);
            }
        });

        jLabel21.setText("Marca:");

        jLabel22.setText("Modelo:");

        jLabel23.setText("Ano:");

        jLabel24.setText("Cor:");

        jLabel25.setText("Combustivel:");

        jLabel26.setText("Preco:");

        javax.swing.GroupLayout CarroLayout = new javax.swing.GroupLayout(Carro);
        Carro.setLayout(CarroLayout);
        CarroLayout.setHorizontalGroup(
            CarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CarroLayout.createSequentialGroup()
                .addGroup(CarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CarroLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel19))
                    .addGroup(CarroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CarroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CarroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(CarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CarroLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CarroLayout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(preco, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(CarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InserirCa)
                            .addGroup(CarroLayout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(combustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        CarroLayout.setVerticalGroup(
            CarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CarroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addGroup(CarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(combustivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel26)
                        .addComponent(preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(InserirCa))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout InserirLayout = new javax.swing.GroupLayout(Inserir);
        Inserir.setLayout(InserirLayout);
        InserirLayout.setHorizontalGroup(
            InserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InserirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InserirLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(180, 180, 180))
                    .addComponent(Carro, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                    .addGroup(InserirLayout.createSequentialGroup()
                        .addComponent(InserirPessoa)
                        .addGap(18, 18, 18)
                        .addComponent(InserirConta)
                        .addGap(18, 18, 18)
                        .addComponent(InserirPessoaConta)
                        .addGap(18, 18, 18)
                        .addComponent(InserirCarros)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(InserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(InserirLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PessoaConta, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(InserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(InserirLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Conta, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(InserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(InserirLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Pessoa, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        InserirLayout.setVerticalGroup(
            InserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InserirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(InserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InserirPessoa)
                    .addComponent(InserirConta)
                    .addComponent(InserirPessoaConta)
                    .addComponent(InserirCarros))
                .addGap(18, 18, 18)
                .addComponent(Carro, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(203, Short.MAX_VALUE))
            .addGroup(InserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InserirLayout.createSequentialGroup()
                    .addContainerGap(276, Short.MAX_VALUE)
                    .addComponent(PessoaConta, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(InserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InserirLayout.createSequentialGroup()
                    .addContainerGap(276, Short.MAX_VALUE)
                    .addComponent(Conta, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(InserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InserirLayout.createSequentialGroup()
                    .addContainerGap(276, Short.MAX_VALUE)
                    .addComponent(Pessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        Principal.addTab("Inserir", Inserir);

        scrollPane.setViewportView(tabela);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "ID", "Nome"
            }
        ));
        scrollPane.setViewportView(tabela);

        opcaoListar.add(ListarPessoas);
        ListarPessoas.setText("Listar Pessoas");
        ListarPessoas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ListarPessoasItemStateChanged(evt);
            }
        });

        opcaoListar.add(ListarContas);
        ListarContas.setText("Listar Contas");
        ListarContas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ListarContasItemStateChanged(evt);
            }
        });

        opcaoListar.add(ListarCarros);
        ListarCarros.setText("Listar Carros");
        ListarCarros.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ListarCarrosItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout ListarLayout = new javax.swing.GroupLayout(Listar);
        Listar.setLayout(ListarLayout);
        ListarLayout.setHorizontalGroup(
            ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListarLayout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(ListarPessoas)
                .addGap(18, 18, 18)
                .addComponent(ListarContas)
                .addGap(18, 18, 18)
                .addComponent(ListarCarros)
                .addGap(157, 157, 157))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane)
                .addContainerGap())
        );
        ListarLayout.setVerticalGroup(
            ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListarPessoas)
                    .addComponent(ListarContas)
                    .addComponent(ListarCarros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 376, Short.MAX_VALUE)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Principal.addTab("Listar", Listar);

        jLabel11.setText("Login");

        jLabel12.setText("Numero de conta:");

        LoginBtn.setText("Entrar");
        LoginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nconta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LoginBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(nconta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoginBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LoginSucesso.setPreferredSize(new java.awt.Dimension(432, 362));

        bemvindo.setText("Bem- Vindo");

        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        jLabel10.setText("Depositar");

        jLabel15.setText("Quantia:");

        depositarbtn.setText("Confirmar");
        depositarbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                depositarbtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout DepositarLayout = new javax.swing.GroupLayout(Depositar);
        Depositar.setLayout(DepositarLayout);
        DepositarLayout.setHorizontalGroup(
            DepositarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DepositarLayout.createSequentialGroup()
                .addGroup(DepositarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DepositarLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel10))
                    .addGroup(DepositarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantiadepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(depositarbtn)))
                .addContainerGap(246, Short.MAX_VALUE))
        );
        DepositarLayout.setVerticalGroup(
            DepositarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DepositarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DepositarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(quantiadepositar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depositarbtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setText("Levantar");

        jLabel14.setText("Quantia:");

        levantarbtn.setText("Confirmar");
        levantarbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                levantarbtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LevantarLayout = new javax.swing.GroupLayout(Levantar);
        Levantar.setLayout(LevantarLayout);
        LevantarLayout.setHorizontalGroup(
            LevantarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LevantarLayout.createSequentialGroup()
                .addGroup(LevantarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LevantarLayout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel13))
                    .addGroup(LevantarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantialevantar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(levantarbtn)))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        LevantarLayout.setVerticalGroup(
            LevantarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LevantarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LevantarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(quantialevantar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(levantarbtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel16.setText("Transferir");

        jLabel17.setText("Numero de conta:");

        jLabel18.setText("Quantia:");

        transferirbtn.setText("Confirmar");
        transferirbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transferirbtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout TransferirLayout = new javax.swing.GroupLayout(Transferir);
        Transferir.setLayout(TransferirLayout);
        TransferirLayout.setHorizontalGroup(
            TransferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransferirLayout.createSequentialGroup()
                .addGroup(TransferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TransferirLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel16))
                    .addGroup(TransferirLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(TransferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TransferirLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(quantia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TransferirLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(conta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(transferirbtn)))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        TransferirLayout.setVerticalGroup(
            TransferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransferirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGroup(TransferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TransferirLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(TransferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(conta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(TransferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(quantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(TransferirLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(transferirbtn)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel31.setText("Lista carros");

        tabelaListaCarros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPaneListaCarros.setViewportView(tabelaListaCarros);

        javax.swing.GroupLayout ListaCarrosLayout = new javax.swing.GroupLayout(ListaCarros);
        ListaCarros.setLayout(ListaCarrosLayout);
        ListaCarrosLayout.setHorizontalGroup(
            ListaCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaCarrosLayout.createSequentialGroup()
                .addGroup(ListaCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ListaCarrosLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel31))
                    .addGroup(ListaCarrosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollPaneListaCarros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ListaCarrosLayout.setVerticalGroup(
            ListaCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaCarrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addGap(18, 18, 18)
                .addComponent(scrollPaneListaCarros, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout ClientesLayout = new javax.swing.GroupLayout(Clientes);
        Clientes.setLayout(ClientesLayout);
        ClientesLayout.setHorizontalGroup(
            ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Depositar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Transferir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Levantar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ListaCarros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ClientesLayout.setVerticalGroup(
            ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Levantar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Depositar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Transferir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ListaCarros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout LoginSucessoLayout = new javax.swing.GroupLayout(LoginSucesso);
        LoginSucesso.setLayout(LoginSucessoLayout);
        LoginSucessoLayout.setHorizontalGroup(
            LoginSucessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginSucessoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bemvindo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 356, Short.MAX_VALUE)
                .addComponent(logout)
                .addContainerGap())
            .addComponent(Clientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LoginSucessoLayout.setVerticalGroup(
            LoginSucessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginSucessoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LoginSucessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bemvindo)
                    .addComponent(logout))
                .addGap(18, 18, 18)
                .addComponent(Clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(LoginSucesso, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LoginLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(LoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(LoginSucesso, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                .addGap(22, 22, 22))
            .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LoginLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(LoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        Principal.addTab("Login", Login);
        LoginSucesso.setEnabled(false);
        LoginSucesso.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Principal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Principal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InserirPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InserirPMouseClicked
        // TODO add your handling code here:
        String nome= nomeP.getText();
        if(ap.size()!=0){
            for(int i=0;i<ap.size();i++){
                if(nome.equals(ap.get(i).getNome())){
                    javax.swing.JOptionPane.showMessageDialog(null,"Este nome ja possui conta\n");
                }else if(i==ap.size()-1 && !nome.equals(ap.get(i).getNome())){
                    javax.swing.JOptionPane.showMessageDialog(null,"Inserido com sucesso\n");
                    func.inserirPessoa(p, ap, nome);
                    break;
                }   
            }
        }else{
            javax.swing.JOptionPane.showMessageDialog(null,"Inserido com sucesso\n");
            func.inserirPessoa(p, ap, nome);
        }
        nomeP.setText("");
    }//GEN-LAST:event_InserirPMouseClicked

    private void InserirCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InserirCMouseClicked
        // TODO add your handling code here:
        
        int opcao=0;
        Double preco = 0.0;
        preco= Double.parseDouble(saldoC.getText());             
        for(int i=0;i<ap.size();i++){
            if(nomeC.getText().equals(ap.get(i).getNome())){
                javax.swing.JOptionPane.showMessageDialog(null,"Saldo adicionado com sucesso\n");
                func.inserirConta(cb,i,preco, acb);
                break;
            }else{
               javax.swing.JOptionPane.showMessageDialog(null,"Este nome nao possui conta\n Insira um nome que ja possua conta\n"); 
            }   
        }
        nomeC.setText("");
        saldoC.setText("");
    }//GEN-LAST:event_InserirCMouseClicked

    private void InserirPCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InserirPCMouseClicked
        // TODO add your handling code here:
        int opcao=0;
        String nome= nomePC.getText();
        if(ap.size()!=0){
            for(int i=0;i<ap.size();i++){
                if(nome.equals(ap.get(i).getNome())){
                   opcao= javax.swing.JOptionPane.showConfirmDialog(null,"Este nome ja possui conta\n "
                           + "Deseja acrescentar mais uma\n");
                    if(opcao==JOptionPane.YES_OPTION){
                        javax.swing.JOptionPane.showMessageDialog(null,"Conta Inserida com sucesso\n");
                        func.inserirConta(cb,i,Double.parseDouble(saldoPC.getText()), acb);
                    }else{
                        break;
                    }
                }else if((i==ap.size()-1) && !(nome.equals(ap.get(i).getNome()))){
                    javax.swing.JOptionPane.showMessageDialog(null,"Inserido Utilizador e Conta "
                            + "com sucesso\n");
                    func.inserirPessoa(p, ap, nome);
                    func.inserirConta(cb,ap.size()-1,Double.parseDouble(saldoPC.getText()), acb);
                    break;
                }   
            }
        }else{
            javax.swing.JOptionPane.showMessageDialog(null,"Inserido Utilizador e Conta com sucesso\n");
            func.inserirPessoa(p, ap, nome);
            func.inserirConta(cb,ap.size()-1,Double.parseDouble(saldoPC.getText()), acb);
        }
        nomePC.setText("");
        saldoPC.setText("");
    }//GEN-LAST:event_InserirPCMouseClicked

    private void ListarPessoasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ListarPessoasItemStateChanged
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();
        for(int i=0;i<model.getRowCount();i++){
            model.removeRow(i);
        }
        model.setColumnCount(0);
        model.setRowCount(0);
        model.addColumn("ID");
        model.addColumn("Nome");
        for(int i=0;i<ap.size();i++){
            Object[] linha ={i,ap.get(i).getNome()};
            model.addRow(linha);
        }
        
    }//GEN-LAST:event_ListarPessoasItemStateChanged

    private void ListarContasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ListarContasItemStateChanged
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();
        for(int i=0;i<model.getRowCount();i++){
            model.removeRow(i);
        }
        model.setColumnCount(0);
        model.setRowCount(0);
        model.addColumn("Numero Conta");
        model.addColumn("Nome Titular");
        model.addColumn("Saldo");
        for(int i=0;i<acb.size();i++){
            Object[] linha ={acb.get(i).getNumero(),acb.get(i).getTitular().getNome(),acb.get(i).getSaldo()+" €"};
            model.addRow(linha);
        }
        
    }//GEN-LAST:event_ListarContasItemStateChanged

    private void InserirPessoaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_InserirPessoaItemStateChanged
        // TODO add your handling code here:
        Pessoa.setVisible(true);
        Pessoa.setEnabled(true);
        PessoaConta.setVisible(false);
        PessoaConta.setEnabled(false);
        Conta.setVisible(false);
        Conta.setEnabled(false);
        Carro.setVisible(false);
        Carro.setEnabled(false);
    }//GEN-LAST:event_InserirPessoaItemStateChanged

    private void InserirPessoaContaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_InserirPessoaContaItemStateChanged
        // TODO add your handling code here:
        Pessoa.setVisible(false);
        Pessoa.setEnabled(false);
        Conta.setVisible(false);
        Conta.setEnabled(false);
        Carro.setVisible(false);
        Carro.setEnabled(false);
        PessoaConta.setVisible(true);
        PessoaConta.setEnabled(true);
    }//GEN-LAST:event_InserirPessoaContaItemStateChanged

    private void InserirContaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_InserirContaItemStateChanged
        // TODO add your handling code here:
        Pessoa.setVisible(false);
        Pessoa.setEnabled(false);
        PessoaConta.setVisible(false);
        PessoaConta.setEnabled(false);
        Carro.setVisible(false);
        Carro.setEnabled(false);
        Conta.setVisible(true);
        Conta.setEnabled(true);
    }//GEN-LAST:event_InserirContaItemStateChanged

    private void LoginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBtnMouseClicked
        // TODO add your handling code here:
        for(int i=0;i<acb.size();i++){
            if(Integer.parseInt(nconta.getText()) == acb.get(i).getNumero()){
                LoginPanel.setEnabled(false);
                LoginPanel.setVisible(false);
                LoginSucesso.setEnabled(true);
                LoginSucesso.setVisible(true);
                bemvindo.setText("Bem Vindo "+acb.get(i).getTitular().getNome());
                contalogin=i;
                if(nconta.getText().equals("0")){
                    Clientes.setEnabled(false);
                    Clientes.setVisible(false);
                    Stand.setEnabled(true);
                    Stand.setVisible(true);
                    
                    DefaultTableModel model = (DefaultTableModel) tabelaCarros.getModel();
                    for(int x=0;x<model.getRowCount();x++){
                        model.removeRow(x);
                    }
                    model.setColumnCount(0);
                    model.setRowCount(0);
                    model.addColumn("Matricula");
                    model.addColumn("Ano");
                    model.addColumn("Marca");
                    model.addColumn("Modelo");
                    model.addColumn("Cor");
                    model.addColumn("Combustivel");
                    model.addColumn("Preco");
                    model.addColumn("Titular");
                    for(int x=0;x<ac.size();x++){
                        if(ap.get(0).getNome().equals(ac.get(x).getTitular().getNome())){
                            Object[] linha ={ac.get(x).getMatricula(),ac.get(x).getAno(),ac.get(x).getMarca(),
                                ac.get(x).getModelo(),ac.get(x).getCor(),ac.get(x).getCombustivel(),ac.get(x).getPreco(),
                                ac.get(x).getTitular().getNome()};
                            model.addRow(linha);
                        }
                    }
                    
                }else{
                    Stand.setEnabled(false);
                    Stand.setVisible(false);
                    Clientes.setEnabled(true);
                    Clientes.setVisible(true);
                    DefaultTableModel model = (DefaultTableModel) tabelaListaCarros.getModel();
                    for(int x=0;x<model.getRowCount();x++){
                        model.removeRow(x);
                    }
                    model.setColumnCount(0);
                    model.setRowCount(0);
                    model.addColumn("Matricula");
                    model.addColumn("Ano");
                    model.addColumn("Marca");
                    model.addColumn("Modelo");
                    model.addColumn("Cor");
                    model.addColumn("Combustivel");
                    model.addColumn("Preco");
                    model.addColumn("Titular");
                    for(int x=0;x<ac.size();x++){
                        if(ap.get(contalogin).getNome().equals(ac.get(x).getTitular().getNome())){
                            Object[] linha ={ac.get(x).getMatricula(),ac.get(x).getAno(),ac.get(x).getMarca(),
                                ac.get(x).getModelo(),ac.get(i).getCor(),ac.get(x).getCombustivel(),ac.get(x).getPreco(),
                                ac.get(x).getTitular().getNome()};
                            model.addRow(linha);
                        }
                    }
                    
                }
                break;
            }else if(i==(acb.size()-1) && (Integer.parseInt(nconta.getText()) != acb.get(i).getNumero())){
                javax.swing.JOptionPane.showMessageDialog(null,"Utilizador inexistente\n");
            }
        }
    }//GEN-LAST:event_LoginBtnMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        LoginSucesso.setEnabled(false);
        LoginSucesso.setVisible(false);
        LoginPanel.setEnabled(true);
        LoginPanel.setVisible(true);
        
        Stand.setEnabled(false);
        Stand.setVisible(false);
        Clientes.setEnabled(false);
        Clientes.setVisible(false);
        if(nconta.getText().equals("0")){
            DefaultTableModel model = (DefaultTableModel) tabelaCarros.getModel();
            for(int x=0;x<model.getRowCount();x++){
                model.removeRow(x);
            }
        }else{
            DefaultTableModel model = (DefaultTableModel) tabelaListaCarros.getModel();
            for(int x=0;x<model.getRowCount();x++){
                model.removeRow(x);
            }
        }
        
        javax.swing.JOptionPane.showMessageDialog(null,"Logout feito com sucesso\n");
        contalogin=-1;
    }//GEN-LAST:event_logoutMouseClicked

    private void levantarbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_levantarbtnMouseClicked
        // TODO add your handling code here:
        if(acb.get(contalogin).getSaldo()>0){
            if(acb.get(contalogin).getSaldo()>=Double.parseDouble(quantialevantar.getText())){
                acb.get(contalogin).setSaldo(
                    acb.get(contalogin).getSaldo()-Double.parseDouble(quantialevantar.getText()));
                javax.swing.JOptionPane.showMessageDialog(null,"Levantamento de "
                    +Double.parseDouble(quantialevantar.getText())+" € feito com sucesso\n");
            }else{
                javax.swing.JOptionPane.showMessageDialog(null,"Saldo de conta inferior à quantia que deseja levantar\n");
            }
        }
        quantialevantar.setText("");
        quantiadepositar.setText("");
        conta.setText("");
        quantia.setText("");
    }//GEN-LAST:event_levantarbtnMouseClicked

    private void depositarbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositarbtnMouseClicked
        // TODO add your handling code here:
        acb.get(contalogin).setSaldo(
            acb.get(contalogin).getSaldo()+Double.parseDouble(quantiadepositar.getText()));
        javax.swing.JOptionPane.showMessageDialog(null,"Deposito de "
            +Double.parseDouble(quantiadepositar.getText())+" € feito com sucesso\n");
        
        quantialevantar.setText("");
        quantiadepositar.setText("");
        conta.setText("");
        quantia.setText("");
    }//GEN-LAST:event_depositarbtnMouseClicked

    private void transferirbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferirbtnMouseClicked
        // TODO add your handling code here:
        for(int i=0;i<acb.size();i++){
            if(Integer.parseInt(conta.getText()) != contalogin){
                if(Integer.parseInt(conta.getText()) == acb.get(i).getNumero()){
                    if(acb.get(contalogin).getSaldo()>0){
                        if(acb.get(contalogin).getSaldo()>=Double.parseDouble(quantia.getText())){
                            acb.get(contalogin).setSaldo(
                                acb.get(contalogin).getSaldo()-Double.parseDouble(quantia.getText()));

                            acb.get(i).setSaldo(
                                acb.get(i).getSaldo()+Double.parseDouble(quantia.getText()));

                            javax.swing.JOptionPane.showMessageDialog(null,"Transferencia feita com sucesso\n");
                            break;
                        }else{
                            javax.swing.JOptionPane.showMessageDialog(null,"Saldo de conta inferior à quantia que deseja transferir\n");
                            break;
                        }
                    }else{
                      javax.swing.JOptionPane.showMessageDialog(null,"Não possui saldo suficiente na "
                              + "conta para fazer uma transferencia\n");
                      break;
                    } 
                }else if(i==(acb.size()-1) && (Integer.parseInt(conta.getText()) != acb.get(i).getNumero())){
                    javax.swing.JOptionPane.showMessageDialog(null,"Utilizador inexistente\n");
                    break;
                }
            }else{
                javax.swing.JOptionPane.showMessageDialog(null,"Nao pode transferir dinheiro para a sua propria conta\n");
                break;
            }
        }
        quantialevantar.setText("");
        quantiadepositar.setText("");
        conta.setText("");
        quantia.setText("");
    }//GEN-LAST:event_transferirbtnMouseClicked

    private void InserirCaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InserirCaMouseClicked
        // TODO add your handling code here:          
        if(ac.size()==0){
            javax.swing.JOptionPane.showMessageDialog(null,"Carro adicionado com sucesso\n");
            func.inserirCarro(c, 0, matricula.getText(), marca.getText(), modelo.getText(),
                Integer.parseInt(ano.getText()), cor.getText(), 
                combustivel.getText(),Double.parseDouble(preco.getText()), ac);
        }else{
            for(int i=0;i<ac.size();i++){
                if(matricula.getText().equals(ac.get(i).getMatricula())){
                    javax.swing.JOptionPane.showMessageDialog(null,"Matricula ja existente\n");
                    break;
                }else if(i==ac.size()-1 && !matricula.getText().equals(ac.get(i).getMatricula())){
                    javax.swing.JOptionPane.showMessageDialog(null,"Carro adicionado com sucesso\n");
                    func.inserirCarro(c, 0, matricula.getText(), marca.getText(), modelo.getText(),
                        Integer.parseInt(ano.getText()), cor.getText(), 
                        combustivel.getText(),Double.parseDouble(preco.getText()), ac);
                    break;
                }
            }
        }
        matricula.setText("");
        ano.setText("");
        marca.setText("");
        modelo.setText("");
        cor.setText("");
        preco.setText("");
        combustivel.setText("");
    }//GEN-LAST:event_InserirCaMouseClicked

    private void InserirCarrosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_InserirCarrosItemStateChanged
        // TODO add your handling code here:
        Pessoa.setVisible(false);
        Pessoa.setEnabled(false);
        PessoaConta.setVisible(false);
        PessoaConta.setEnabled(false);
        Carro.setVisible(true);
        Carro.setEnabled(true);
        Conta.setVisible(false);
        Conta.setEnabled(false);
    }//GEN-LAST:event_InserirCarrosItemStateChanged

    private void ListarCarrosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ListarCarrosItemStateChanged
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();
        for(int i=0;i<model.getRowCount();i++){
            model.removeRow(i);
        }
        model.setColumnCount(0);
        model.setRowCount(0);
        model.addColumn("Matricula");
        model.addColumn("Ano");
        model.addColumn("Marca");
        model.addColumn("Modelo");
        model.addColumn("Cor");
        model.addColumn("Combustivel");
        model.addColumn("Preco");
        model.addColumn("Titular");
        for(int i=0;i<ac.size();i++){
            Object[] linha ={ac.get(i).getMatricula(),ac.get(i).getAno(),ac.get(i).getMarca(),
                ac.get(i).getModelo(),ac.get(i).getCor(),ac.get(i).getCombustivel(),ac.get(i).getPreco(),
                ac.get(i).getTitular().getNome()};
            model.addRow(linha);
        }
    }//GEN-LAST:event_ListarCarrosItemStateChanged

    private void tabelaCarrosComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tabelaCarrosComponentShown
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabelaCarros.getModel();
        for(int i=0;i<model.getRowCount();i++){
            model.removeRow(i);
        }
        model.setColumnCount(0);
        model.setRowCount(0);
        model.addColumn("Matricula");
        model.addColumn("Ano");
        model.addColumn("Marca");
        model.addColumn("Modelo");
        model.addColumn("Cor");
        model.addColumn("Combustivel");
        model.addColumn("Preco");
        model.addColumn("Titular");
        for(int i=0;i<ac.size();i++){
            if(ap.get(0).getNome().equals(ac.get(i).getTitular().getNome())){
                Object[] linha ={ac.get(i).getMatricula(),ac.get(i).getAno(),ac.get(i).getMarca(),
                    ac.get(i).getModelo(),ac.get(i).getCor(),ac.get(i).getCombustivel(),ac.get(i).getPreco(),
                    ac.get(i).getTitular().getNome()};
                model.addRow(linha);
            }
        }
    }//GEN-LAST:event_tabelaCarrosComponentShown

    private void venderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_venderMouseClicked
        // TODO add your handling code here:
        int comprador = Integer.parseInt(contaComprador.getText());
        for(int i=0;i<acb.size();i++){
            //if(acb.get(i).getNumero()!=0){
            if(comprador!=0){
                if(acb.get(i).getNumero()==comprador){
                    //int comp=i;
                    DefaultTableModel model = (DefaultTableModel) tabelaCarros.getModel();
                    if(tabelaCarros.getSelectedRow()==-1){
                        javax.swing.JOptionPane.showMessageDialog(null,"Nao existe carro selecionado\n Selecione um carro por favor");
                        break;
                    }
                    javax.swing.JOptionPane.showMessageDialog(null,model.getValueAt(tabelaCarros.getSelectedRow(),6));
                    if(acb.get(i).getSaldo()>= ac.get(tabelaCarros.getSelectedRow()).getPreco()){
                        acb.get(i).setSaldo(acb.get(i).getSaldo()-ac.get(tabelaCarros.getSelectedRow()).getPreco());
                        acb.get(0).setSaldo(acb.get(0).getSaldo()+ac.get(tabelaCarros.getSelectedRow()).getPreco());
                        ac.get(tabelaCarros.getSelectedRow()).setTitular(acb.get(i).getTitular());
                        func.inserirVenda(ac.get(tabelaCarros.getSelectedRow()) , acb.get(i).getTitular(),
                                ac.get(tabelaCarros.getSelectedRow()).getPreco(), data.getText());
                        javax.swing.JOptionPane.showMessageDialog(null,"Carro vendido por "+ac.get(tabelaCarros.getSelectedRow()).getPreco()+" €");
                    }else{
                        javax.swing.JOptionPane.showMessageDialog(null,"Saldo Insuficiente na conta\n");
                    }
                    break;
                }else if(i==(acb.size()-1) && acb.get(i).getNumero()!=comprador){
                    javax.swing.JOptionPane.showMessageDialog(null,"Conta Inexistente\n");
                    break;
                }
                
            }else{
                javax.swing.JOptionPane.showMessageDialog(null,"Nao se pode vender um carro a si proprio\n");
                break;
            }
        }
        
        DefaultTableModel modelCarros = (DefaultTableModel) tabelaCarros.getModel();
        for(int i=0;i<modelCarros.getRowCount();i++){
            modelCarros.removeRow(i);
        }
        modelCarros.setColumnCount(0);
        modelCarros.setRowCount(0);
        modelCarros.addColumn("Matricula");
        modelCarros.addColumn("Ano");
        modelCarros.addColumn("Marca");
        modelCarros.addColumn("Modelo");
        modelCarros.addColumn("Cor");
        modelCarros.addColumn("Combustivel");
        modelCarros.addColumn("Preco");
        modelCarros.addColumn("Titular");
        for(int i=0;i<ac.size();i++){
            if(ap.get(0).getNome().equals(ac.get(i).getTitular().getNome())){
                Object[] linha ={ac.get(i).getMatricula(),ac.get(i).getAno(),ac.get(i).getMarca(),
                    ac.get(i).getModelo(),ac.get(i).getCor(),ac.get(i).getCombustivel(),ac.get(i).getPreco(),
                    ac.get(i).getTitular().getNome()};
                modelCarros.addRow(linha);
            }
        }
         
        DefaultTableModel model = (DefaultTableModel) tabelaVendas.getModel();
        for(int i=0;i<model.getRowCount();i++){
            model.removeRow(i);
        }
        model.setColumnCount(0);
        model.setRowCount(0);
        model.addColumn("Carro");
        model.addColumn("Titular");
        model.addColumn("Preco");
        model.addColumn("Data");
        for(int i=0;i<av.size();i++){
            Object[] linha ={av.get(i).getCarroVendido().getMatricula(),av.get(i).getComprador().getNome(),av.get(i).getPreco(),
                av.get(i).getData()};
            model.addRow(linha);
        }
    }//GEN-LAST:event_venderMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Carro;
    private javax.swing.JPanel Clientes;
    private javax.swing.JPanel Conta;
    private javax.swing.JPanel Depositar;
    private javax.swing.JPanel Inserir;
    private javax.swing.JButton InserirC;
    private javax.swing.JButton InserirCa;
    private javax.swing.JRadioButton InserirCarros;
    private javax.swing.JRadioButton InserirConta;
    private javax.swing.JButton InserirP;
    private javax.swing.JButton InserirPC;
    private javax.swing.JRadioButton InserirPessoa;
    private javax.swing.JRadioButton InserirPessoaConta;
    private javax.swing.JPanel Levantar;
    private javax.swing.JPanel ListaCarros;
    private javax.swing.JPanel Listar;
    private javax.swing.JRadioButton ListarCarros;
    private javax.swing.JRadioButton ListarContas;
    private javax.swing.JRadioButton ListarPessoas;
    private javax.swing.JPanel Login;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JPanel LoginSucesso;
    private javax.swing.JPanel Pessoa;
    private javax.swing.JPanel PessoaConta;
    private javax.swing.JTabbedPane Principal;
    private javax.swing.JPanel Stand;
    private javax.swing.JPanel Transferir;
    private javax.swing.JTextField ano;
    private javax.swing.JLabel bemvindo;
    private javax.swing.JTextField combustivel;
    private javax.swing.JTextField conta;
    private javax.swing.JTextField contaComprador;
    private javax.swing.JTextField cor;
    private javax.swing.JTextField data;
    private javax.swing.JButton depositarbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton levantarbtn;
    private javax.swing.JButton logout;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField matricula;
    private javax.swing.JTextField modelo;
    private javax.swing.JTextField nconta;
    private javax.swing.JTextField nomeC;
    private javax.swing.JTextField nomeP;
    private javax.swing.JTextField nomePC;
    private javax.swing.ButtonGroup opcaoInserir;
    private javax.swing.ButtonGroup opcaoListar;
    private javax.swing.JTextField preco;
    private javax.swing.JTextField quantia;
    private javax.swing.JTextField quantiadepositar;
    private javax.swing.JTextField quantialevantar;
    private javax.swing.JTextField saldoC;
    private javax.swing.JTextField saldoPC;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JScrollPane scrollPaneCarros;
    private javax.swing.JScrollPane scrollPaneListaCarros;
    private javax.swing.JScrollPane scrollPaneVendas;
    private javax.swing.JTable tabela;
    private javax.swing.JTable tabelaCarros;
    private javax.swing.JTable tabelaListaCarros;
    private javax.swing.JTable tabelaVendas;
    private javax.swing.JButton transferirbtn;
    private javax.swing.JButton vender;
    // End of variables declaration//GEN-END:variables
}
